# use Ubuntu 14.04 (Trusty) image, it contains the latest JDK
sudo: required
dist: trusty

before_install:
  # start X-server for GUI tests (xvfb)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

language: java

jdk:
  - oraclejdk9
addons:
  sonarcloud:
    organization: "nesqwik-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - mvn test -B
  - sonar-scanner
